name: .NET

on: workflow_dispatch

jobs:
  build:
    container: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app
      run: dotnet build -c release --no-restore --verbosity normal ./dotnet-issue-showcase/dotnet-issue-showcase.csproj
    - name: Build tests
      run: dotnet build -c release --no-restore --verbosity normal ./tests/tests.csproj
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
