name: .NET

on: workflow_dispatch

jobs:
  build:
    container: mcr.microsoft.com/dotnet/sdk:3.1-alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
